// Servidor auxiliar de mídia. Requer Node.js 22+ e HTTPS na frente dele.
import http from 'node:http';
import https from 'node:https';
import dns from 'node:dns/promises';
import {timingSafeEqual} from 'node:crypto';
const secret=process.env.RELAY_KEY,port=Number(process.env.PORT||8080);
if(!secret||secret.length<32)throw Error('Configure RELAY_KEY com pelo menos 32 caracteres.');
const allowedHosts=(process.env.ALLOWED_HOSTS||'hmns.top,*.hmns.top,iptvmais.one,limitv.me,*.limitv.me,dns.playerli.me').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);
function publicIP(ip){const a=ip.split('.').map(Number);return a.length===4&&a.every(x=>Number.isInteger(x)&&x>=0&&x<=255)&&a[0]>0&&a[0]<224&&a[0]!==10&&a[0]!==127&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&a[1]===168)&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&(a[1]===18||a[1]===19))}
function authenticated(req){const b=Buffer.from(req.headers.authorization||''),a=Buffer.from('Bearer '+secret);return a.length===b.length&&timingSafeEqual(a,b)}
async function check(url){if(!['http:','https:'].includes(url.protocol)||url.username||url.password||!['','80','443'].includes(url.port))throw Error('Destino inválido');const host=url.hostname;if(!publicIP(host)&&!allowedHosts.some(x=>x.startsWith('*.')?host.endsWith(x.slice(1)):host===x))throw Error('Destino não permitido');const addresses=await dns.lookup(host,{all:true,family:4});if(!addresses.length||addresses.some(x=>!publicIP(x.address)))throw Error('Destino privado');return addresses[0].address}
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,Range','Access-Control-Expose-Headers':'Content-Length,Content-Range,Accept-Ranges,X-Kiflix-Final-URL'};const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,cors);res.end();return}if(req.url==='/health'&&req.method==='GET'){res.writeHead(200,{...cors,'Content-Type':'application/json'});res.end('{"ok":true}');return}if(req.url!=='/fetch'||req.method!=='POST'||!authenticated(req)){res.writeHead(401);res.end();return}let outgoing;try{let body='';for await(const chunk of req){body+=chunk;if(body.length>16000)throw Error('Corpo excessivo')}const data=JSON.parse(body);let url=new URL(data.url);const range=data.range;if(range&&!/^bytes=\d*-\d*$/.test(range))throw Error('Range inválido');
 for(let i=0;i<8;i++){const ip=await check(url);const upstream=await new Promise((resolve,reject)=>{outgoing=(url.protocol==='https:'?https:http).request(url,{method:'GET',headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','Accept':'*/*','Accept-Encoding':'identity','Referer':url.origin+'/',...(range?{Range:range}:{}),...(publicIP(url.hostname)?{Host:process.env.ORIGIN_HOST||'hmns.top'}:{})},servername:publicIP(url.hostname)?(process.env.ORIGIN_HOST||'hmns.top'):url.hostname,lookup:(_h,opts,cb)=>opts.all?cb(null,[{address:ip,family:4}]):cb(null,ip,4)},resolve);outgoing.on('error',reject);outgoing.setTimeout(25000,()=>outgoing.destroy(Error('Tempo excedido')));outgoing.end()});if([301,302,303,307,308].includes(upstream.statusCode)){const next=upstream.headers.location;upstream.destroy();if(!next)throw Error('Redirecionamento inválido');url=new URL(next,url);continue}
 const headers={...cors,'Cache-Control':'no-store','X-Kiflix-Final-URL':Buffer.from(url.href).toString('base64')};for(const name of ['content-type','content-length','content-range','accept-ranges'])if(upstream.headers[name])headers[name]=upstream.headers[name];res.writeHead(upstream.statusCode,headers);res.on('close',()=>upstream.destroy());upstream.on('error',()=>res.destroy());upstream.pipe(res);return}throw Error('Redirecionamentos excessivos');
 }catch{outgoing?.destroy();if(!res.headersSent)res.writeHead(502,{...cors,'Content-Type':'application/json'});res.end('{"error":"Não foi possível acessar a origem de mídia."}')}});
server.requestTimeout=30000;server.headersTimeout=10000;server.listen(port,'0.0.0.0',()=>console.log('Relay de mídia iniciado na porta '+port));
